name: Deploy

on:
  workflow_run:
    workflows:
      - Laravel Pint
    types:
      - completed
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Deploy to Coolify
        run: |
          curl --location ${{ vars.DEPLOY_URL }} --header "Authorization: Bearer ${{ secrets.COOLIFY_SECRET }}"